/*
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com
 *
 * The version of the OpenAPI document: 1.75.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.ynab_api_client.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.example.ynab_api_client.client.model.BudgetSummary;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.example.ynab_api_client.client.invoker.ApiClient;
/**
 * BudgetSummaryResponseData
 */
@JsonPropertyOrder({
  BudgetSummaryResponseData.JSON_PROPERTY_BUDGETS,
  BudgetSummaryResponseData.JSON_PROPERTY_DEFAULT_BUDGET
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-07-01T21:45:22.500220+02:00[Europe/Zurich]", comments = "Generator version: 7.14.0")
public class BudgetSummaryResponseData {
  public static final String JSON_PROPERTY_BUDGETS = "budgets";
  @jakarta.annotation.Nonnull
  private List<BudgetSummary> budgets = new ArrayList<>();

  public static final String JSON_PROPERTY_DEFAULT_BUDGET = "default_budget";
  @jakarta.annotation.Nullable
  private BudgetSummary defaultBudget;

  public BudgetSummaryResponseData() { 
  }

  public BudgetSummaryResponseData budgets(@jakarta.annotation.Nonnull List<BudgetSummary> budgets) {
    this.budgets = budgets;
    return this;
  }

  public BudgetSummaryResponseData addBudgetsItem(BudgetSummary budgetsItem) {
    if (this.budgets == null) {
      this.budgets = new ArrayList<>();
    }
    this.budgets.add(budgetsItem);
    return this;
  }

  /**
   * Get budgets
   * @return budgets
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_BUDGETS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<BudgetSummary> getBudgets() {
    return budgets;
  }


  @JsonProperty(JSON_PROPERTY_BUDGETS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBudgets(@jakarta.annotation.Nonnull List<BudgetSummary> budgets) {
    this.budgets = budgets;
  }


  public BudgetSummaryResponseData defaultBudget(@jakarta.annotation.Nullable BudgetSummary defaultBudget) {
    this.defaultBudget = defaultBudget;
    return this;
  }

  /**
   * Get defaultBudget
   * @return defaultBudget
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DEFAULT_BUDGET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BudgetSummary getDefaultBudget() {
    return defaultBudget;
  }


  @JsonProperty(JSON_PROPERTY_DEFAULT_BUDGET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDefaultBudget(@jakarta.annotation.Nullable BudgetSummary defaultBudget) {
    this.defaultBudget = defaultBudget;
  }


  /**
   * Return true if this BudgetSummaryResponse_data object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BudgetSummaryResponseData budgetSummaryResponseData = (BudgetSummaryResponseData) o;
    return Objects.equals(this.budgets, budgetSummaryResponseData.budgets) &&
        Objects.equals(this.defaultBudget, budgetSummaryResponseData.defaultBudget);
  }

  @Override
  public int hashCode() {
    return Objects.hash(budgets, defaultBudget);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BudgetSummaryResponseData {\n");
    sb.append("    budgets: ").append(toIndentedString(budgets)).append("\n");
    sb.append("    defaultBudget: ").append(toIndentedString(defaultBudget)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `budgets` to the URL query string
    if (getBudgets() != null) {
      for (int i = 0; i < getBudgets().size(); i++) {
        if (getBudgets().get(i) != null) {
          joiner.add(getBudgets().get(i).toUrlQueryString(String.format("%sbudgets%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `default_budget` to the URL query string
    if (getDefaultBudget() != null) {
      joiner.add(getDefaultBudget().toUrlQueryString(prefix + "default_budget" + suffix));
    }

    return joiner.toString();
  }
}

