/*
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com
 *
 * The version of the OpenAPI document: 1.75.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.ynab_api_client.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.example.ynab_api_client.client.invoker.ApiClient;
/**
 * BulkResponseDataBulk
 */
@JsonPropertyOrder({
  BulkResponseDataBulk.JSON_PROPERTY_TRANSACTION_IDS,
  BulkResponseDataBulk.JSON_PROPERTY_DUPLICATE_IMPORT_IDS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-07-01T21:45:22.500220+02:00[Europe/Zurich]", comments = "Generator version: 7.14.0")
public class BulkResponseDataBulk {
  public static final String JSON_PROPERTY_TRANSACTION_IDS = "transaction_ids";
  @jakarta.annotation.Nonnull
  private List<String> transactionIds = new ArrayList<>();

  public static final String JSON_PROPERTY_DUPLICATE_IMPORT_IDS = "duplicate_import_ids";
  @jakarta.annotation.Nonnull
  private List<String> duplicateImportIds = new ArrayList<>();

  public BulkResponseDataBulk() { 
  }

  public BulkResponseDataBulk transactionIds(@jakarta.annotation.Nonnull List<String> transactionIds) {
    this.transactionIds = transactionIds;
    return this;
  }

  public BulkResponseDataBulk addTransactionIdsItem(String transactionIdsItem) {
    if (this.transactionIds == null) {
      this.transactionIds = new ArrayList<>();
    }
    this.transactionIds.add(transactionIdsItem);
    return this;
  }

  /**
   * The list of Transaction ids that were created.
   * @return transactionIds
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TRANSACTION_IDS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<String> getTransactionIds() {
    return transactionIds;
  }


  @JsonProperty(JSON_PROPERTY_TRANSACTION_IDS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTransactionIds(@jakarta.annotation.Nonnull List<String> transactionIds) {
    this.transactionIds = transactionIds;
  }


  public BulkResponseDataBulk duplicateImportIds(@jakarta.annotation.Nonnull List<String> duplicateImportIds) {
    this.duplicateImportIds = duplicateImportIds;
    return this;
  }

  public BulkResponseDataBulk addDuplicateImportIdsItem(String duplicateImportIdsItem) {
    if (this.duplicateImportIds == null) {
      this.duplicateImportIds = new ArrayList<>();
    }
    this.duplicateImportIds.add(duplicateImportIdsItem);
    return this;
  }

  /**
   * If any Transactions were not created because they had an &#x60;import_id&#x60; matching a transaction already on the same account, the specified import_id(s) will be included in this list.
   * @return duplicateImportIds
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_DUPLICATE_IMPORT_IDS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<String> getDuplicateImportIds() {
    return duplicateImportIds;
  }


  @JsonProperty(JSON_PROPERTY_DUPLICATE_IMPORT_IDS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDuplicateImportIds(@jakarta.annotation.Nonnull List<String> duplicateImportIds) {
    this.duplicateImportIds = duplicateImportIds;
  }


  /**
   * Return true if this BulkResponse_data_bulk object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BulkResponseDataBulk bulkResponseDataBulk = (BulkResponseDataBulk) o;
    return Objects.equals(this.transactionIds, bulkResponseDataBulk.transactionIds) &&
        Objects.equals(this.duplicateImportIds, bulkResponseDataBulk.duplicateImportIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(transactionIds, duplicateImportIds);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BulkResponseDataBulk {\n");
    sb.append("    transactionIds: ").append(toIndentedString(transactionIds)).append("\n");
    sb.append("    duplicateImportIds: ").append(toIndentedString(duplicateImportIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `transaction_ids` to the URL query string
    if (getTransactionIds() != null) {
      for (int i = 0; i < getTransactionIds().size(); i++) {
        joiner.add(String.format("%stransaction_ids%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getTransactionIds().get(i)))));
      }
    }

    // add `duplicate_import_ids` to the URL query string
    if (getDuplicateImportIds() != null) {
      for (int i = 0; i < getDuplicateImportIds().size(); i++) {
        joiner.add(String.format("%sduplicate_import_ids%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getDuplicateImportIds().get(i)))));
      }
    }

    return joiner.toString();
  }
}

