/*
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com
 *
 * The version of the OpenAPI document: 1.75.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.ynab_api_client.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.example.ynab_api_client.client.model.BulkResponseDataBulk;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.example.ynab_api_client.client.invoker.ApiClient;
/**
 * BulkResponseData
 */
@JsonPropertyOrder({
  BulkResponseData.JSON_PROPERTY_BULK
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-07-01T21:45:22.500220+02:00[Europe/Zurich]", comments = "Generator version: 7.14.0")
public class BulkResponseData {
  public static final String JSON_PROPERTY_BULK = "bulk";
  @jakarta.annotation.Nonnull
  private BulkResponseDataBulk bulk;

  public BulkResponseData() { 
  }

  public BulkResponseData bulk(@jakarta.annotation.Nonnull BulkResponseDataBulk bulk) {
    this.bulk = bulk;
    return this;
  }

  /**
   * Get bulk
   * @return bulk
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_BULK)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public BulkResponseDataBulk getBulk() {
    return bulk;
  }


  @JsonProperty(JSON_PROPERTY_BULK)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBulk(@jakarta.annotation.Nonnull BulkResponseDataBulk bulk) {
    this.bulk = bulk;
  }


  /**
   * Return true if this BulkResponse_data object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BulkResponseData bulkResponseData = (BulkResponseData) o;
    return Objects.equals(this.bulk, bulkResponseData.bulk);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bulk);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BulkResponseData {\n");
    sb.append("    bulk: ").append(toIndentedString(bulk)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `bulk` to the URL query string
    if (getBulk() != null) {
      joiner.add(getBulk().toUrlQueryString(prefix + "bulk" + suffix));
    }

    return joiner.toString();
  }
}

