/*
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com
 *
 * The version of the OpenAPI document: 1.75.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.ynab_api_client.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.example.ynab_api_client.client.invoker.ApiClient;
/**
 * SaveMonthCategory
 */
@JsonPropertyOrder({
  SaveMonthCategory.JSON_PROPERTY_BUDGETED
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-07-01T21:45:22.500220+02:00[Europe/Zurich]", comments = "Generator version: 7.14.0")
public class SaveMonthCategory {
  public static final String JSON_PROPERTY_BUDGETED = "budgeted";
  @jakarta.annotation.Nonnull
  private Long budgeted;

  public SaveMonthCategory() { 
  }

  public SaveMonthCategory budgeted(@jakarta.annotation.Nonnull Long budgeted) {
    this.budgeted = budgeted;
    return this;
  }

  /**
   * Budgeted amount in milliunits format
   * @return budgeted
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_BUDGETED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Long getBudgeted() {
    return budgeted;
  }


  @JsonProperty(JSON_PROPERTY_BUDGETED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBudgeted(@jakarta.annotation.Nonnull Long budgeted) {
    this.budgeted = budgeted;
  }


  /**
   * Return true if this SaveMonthCategory object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SaveMonthCategory saveMonthCategory = (SaveMonthCategory) o;
    return Objects.equals(this.budgeted, saveMonthCategory.budgeted);
  }

  @Override
  public int hashCode() {
    return Objects.hash(budgeted);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SaveMonthCategory {\n");
    sb.append("    budgeted: ").append(toIndentedString(budgeted)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `budgeted` to the URL query string
    if (getBudgeted() != null) {
      joiner.add(String.format("%sbudgeted%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getBudgeted()))));
    }

    return joiner.toString();
  }
}

