/*
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com
 *
 * The version of the OpenAPI document: 1.75.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.ynab_api_client.client.api;

import com.example.ynab_api_client.client.invoker.ApiException;
import com.example.ynab_api_client.client.model.ErrorResponse;
import com.example.ynab_api_client.client.model.PayeeLocationResponse;
import com.example.ynab_api_client.client.model.PayeeLocationsResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for PayeeLocationsApi
 */
@Disabled
public class PayeeLocationsApiTest {

    private final PayeeLocationsApi api = new PayeeLocationsApi();

    
    /**
     * Single payee location
     *
     * Returns a single payee location
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getPayeeLocationByIdTest() throws ApiException {
        String budgetId = null;
        String payeeLocationId = null;
        PayeeLocationResponse response = 
        api.getPayeeLocationById(budgetId, payeeLocationId);
        
        // TODO: test validations
    }
    
    /**
     * List payee locations
     *
     * Returns all payee locations
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getPayeeLocationsTest() throws ApiException {
        String budgetId = null;
        PayeeLocationsResponse response = 
        api.getPayeeLocations(budgetId);
        
        // TODO: test validations
    }
    
    /**
     * List locations for a payee
     *
     * Returns all payee locations for a specified payee
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getPayeeLocationsByPayeeTest() throws ApiException {
        String budgetId = null;
        String payeeId = null;
        PayeeLocationsResponse response = 
        api.getPayeeLocationsByPayee(budgetId, payeeId);
        
        // TODO: test validations
    }
    
}
