/*
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com
 *
 * The version of the OpenAPI document: 1.75.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.ynab_api_client.client.api;

import com.example.ynab_api_client.client.invoker.ApiException;
import com.example.ynab_api_client.client.model.ErrorResponse;
import com.example.ynab_api_client.client.model.PostScheduledTransactionWrapper;
import com.example.ynab_api_client.client.model.PutScheduledTransactionWrapper;
import com.example.ynab_api_client.client.model.ScheduledTransactionResponse;
import com.example.ynab_api_client.client.model.ScheduledTransactionsResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for ScheduledTransactionsApi
 */
@Disabled
public class ScheduledTransactionsApiTest {

    private final ScheduledTransactionsApi api = new ScheduledTransactionsApi();

    
    /**
     * Create a single scheduled transaction
     *
     * Creates a single scheduled transaction (a transaction with a future date).
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createScheduledTransactionTest() throws ApiException {
        String budgetId = null;
        PostScheduledTransactionWrapper data = null;
        ScheduledTransactionResponse response = 
        api.createScheduledTransaction(budgetId, data);
        
        // TODO: test validations
    }
    
    /**
     * Deletes an existing scheduled transaction
     *
     * Deletes a scheduled transaction
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteScheduledTransactionTest() throws ApiException {
        String budgetId = null;
        String scheduledTransactionId = null;
        ScheduledTransactionResponse response = 
        api.deleteScheduledTransaction(budgetId, scheduledTransactionId);
        
        // TODO: test validations
    }
    
    /**
     * Single scheduled transaction
     *
     * Returns a single scheduled transaction
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getScheduledTransactionByIdTest() throws ApiException {
        String budgetId = null;
        String scheduledTransactionId = null;
        ScheduledTransactionResponse response = 
        api.getScheduledTransactionById(budgetId, scheduledTransactionId);
        
        // TODO: test validations
    }
    
    /**
     * List scheduled transactions
     *
     * Returns all scheduled transactions
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getScheduledTransactionsTest() throws ApiException {
        String budgetId = null;
        Long lastKnowledgeOfServer = null;
        ScheduledTransactionsResponse response = 
        api.getScheduledTransactions(budgetId, lastKnowledgeOfServer);
        
        // TODO: test validations
    }
    
    /**
     * Updates an existing scheduled transaction
     *
     * Updates a single scheduled transaction
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateScheduledTransactionTest() throws ApiException {
        String budgetId = null;
        String scheduledTransactionId = null;
        PutScheduledTransactionWrapper putScheduledTransactionWrapper = null;
        ScheduledTransactionResponse response = 
        api.updateScheduledTransaction(budgetId, scheduledTransactionId, putScheduledTransactionWrapper);
        
        // TODO: test validations
    }
    
}
