/*
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com
 *
 * The version of the OpenAPI document: 1.75.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.ynab_api_client.client.model;

import com.example.ynab_api_client.client.model.BudgetDetail;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for BudgetDetailResponseData
 */
class BudgetDetailResponseDataTest {
    private final BudgetDetailResponseData model = new BudgetDetailResponseData();

    /**
     * Model tests for BudgetDetailResponseData
     */
    @Test
    void testBudgetDetailResponseData() {
        // TODO: test BudgetDetailResponseData
    }

    /**
     * Test the property 'budget'
     */
    @Test
    void budgetTest() {
        // TODO: test budget
    }

    /**
     * Test the property 'serverKnowledge'
     */
    @Test
    void serverKnowledgeTest() {
        // TODO: test serverKnowledge
    }

}
