/*
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com
 *
 * The version of the OpenAPI document: 1.75.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.ynab_api_client.client.model;

import com.example.ynab_api_client.client.model.Account;
import com.example.ynab_api_client.client.model.Category;
import com.example.ynab_api_client.client.model.CategoryGroup;
import com.example.ynab_api_client.client.model.CurrencyFormat;
import com.example.ynab_api_client.client.model.DateFormat;
import com.example.ynab_api_client.client.model.MonthDetail;
import com.example.ynab_api_client.client.model.Payee;
import com.example.ynab_api_client.client.model.PayeeLocation;
import com.example.ynab_api_client.client.model.ScheduledSubTransaction;
import com.example.ynab_api_client.client.model.ScheduledTransactionSummary;
import com.example.ynab_api_client.client.model.SubTransaction;
import com.example.ynab_api_client.client.model.TransactionSummary;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for BudgetDetail
 */
class BudgetDetailTest {
    private final BudgetDetail model = new BudgetDetail();

    /**
     * Model tests for BudgetDetail
     */
    @Test
    void testBudgetDetail() {
        // TODO: test BudgetDetail
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'lastModifiedOn'
     */
    @Test
    void lastModifiedOnTest() {
        // TODO: test lastModifiedOn
    }

    /**
     * Test the property 'firstMonth'
     */
    @Test
    void firstMonthTest() {
        // TODO: test firstMonth
    }

    /**
     * Test the property 'lastMonth'
     */
    @Test
    void lastMonthTest() {
        // TODO: test lastMonth
    }

    /**
     * Test the property 'dateFormat'
     */
    @Test
    void dateFormatTest() {
        // TODO: test dateFormat
    }

    /**
     * Test the property 'currencyFormat'
     */
    @Test
    void currencyFormatTest() {
        // TODO: test currencyFormat
    }

    /**
     * Test the property 'accounts'
     */
    @Test
    void accountsTest() {
        // TODO: test accounts
    }

    /**
     * Test the property 'payees'
     */
    @Test
    void payeesTest() {
        // TODO: test payees
    }

    /**
     * Test the property 'payeeLocations'
     */
    @Test
    void payeeLocationsTest() {
        // TODO: test payeeLocations
    }

    /**
     * Test the property 'categoryGroups'
     */
    @Test
    void categoryGroupsTest() {
        // TODO: test categoryGroups
    }

    /**
     * Test the property 'categories'
     */
    @Test
    void categoriesTest() {
        // TODO: test categories
    }

    /**
     * Test the property 'months'
     */
    @Test
    void monthsTest() {
        // TODO: test months
    }

    /**
     * Test the property 'transactions'
     */
    @Test
    void transactionsTest() {
        // TODO: test transactions
    }

    /**
     * Test the property 'subtransactions'
     */
    @Test
    void subtransactionsTest() {
        // TODO: test subtransactions
    }

    /**
     * Test the property 'scheduledTransactions'
     */
    @Test
    void scheduledTransactionsTest() {
        // TODO: test scheduledTransactions
    }

    /**
     * Test the property 'scheduledSubtransactions'
     */
    @Test
    void scheduledSubtransactionsTest() {
        // TODO: test scheduledSubtransactions
    }

}
