/*
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com
 *
 * The version of the OpenAPI document: 1.75.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.ynab_api_client.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.LocalDate;
import java.util.Arrays;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Category
 */
class CategoryTest {
    private final Category model = new Category();

    /**
     * Model tests for Category
     */
    @Test
    void testCategory() {
        // TODO: test Category
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'categoryGroupId'
     */
    @Test
    void categoryGroupIdTest() {
        // TODO: test categoryGroupId
    }

    /**
     * Test the property 'categoryGroupName'
     */
    @Test
    void categoryGroupNameTest() {
        // TODO: test categoryGroupName
    }

    /**
     * Test the property 'name'
     */
    @Test
    void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'hidden'
     */
    @Test
    void hiddenTest() {
        // TODO: test hidden
    }

    /**
     * Test the property 'originalCategoryGroupId'
     */
    @Test
    void originalCategoryGroupIdTest() {
        // TODO: test originalCategoryGroupId
    }

    /**
     * Test the property 'note'
     */
    @Test
    void noteTest() {
        // TODO: test note
    }

    /**
     * Test the property 'budgeted'
     */
    @Test
    void budgetedTest() {
        // TODO: test budgeted
    }

    /**
     * Test the property 'activity'
     */
    @Test
    void activityTest() {
        // TODO: test activity
    }

    /**
     * Test the property 'balance'
     */
    @Test
    void balanceTest() {
        // TODO: test balance
    }

    /**
     * Test the property 'goalType'
     */
    @Test
    void goalTypeTest() {
        // TODO: test goalType
    }

    /**
     * Test the property 'goalNeedsWholeAmount'
     */
    @Test
    void goalNeedsWholeAmountTest() {
        // TODO: test goalNeedsWholeAmount
    }

    /**
     * Test the property 'goalDay'
     */
    @Test
    void goalDayTest() {
        // TODO: test goalDay
    }

    /**
     * Test the property 'goalCadence'
     */
    @Test
    void goalCadenceTest() {
        // TODO: test goalCadence
    }

    /**
     * Test the property 'goalCadenceFrequency'
     */
    @Test
    void goalCadenceFrequencyTest() {
        // TODO: test goalCadenceFrequency
    }

    /**
     * Test the property 'goalCreationMonth'
     */
    @Test
    void goalCreationMonthTest() {
        // TODO: test goalCreationMonth
    }

    /**
     * Test the property 'goalTarget'
     */
    @Test
    void goalTargetTest() {
        // TODO: test goalTarget
    }

    /**
     * Test the property 'goalTargetMonth'
     */
    @Test
    void goalTargetMonthTest() {
        // TODO: test goalTargetMonth
    }

    /**
     * Test the property 'goalPercentageComplete'
     */
    @Test
    void goalPercentageCompleteTest() {
        // TODO: test goalPercentageComplete
    }

    /**
     * Test the property 'goalMonthsToBudget'
     */
    @Test
    void goalMonthsToBudgetTest() {
        // TODO: test goalMonthsToBudget
    }

    /**
     * Test the property 'goalUnderFunded'
     */
    @Test
    void goalUnderFundedTest() {
        // TODO: test goalUnderFunded
    }

    /**
     * Test the property 'goalOverallFunded'
     */
    @Test
    void goalOverallFundedTest() {
        // TODO: test goalOverallFunded
    }

    /**
     * Test the property 'goalOverallLeft'
     */
    @Test
    void goalOverallLeftTest() {
        // TODO: test goalOverallLeft
    }

    /**
     * Test the property 'deleted'
     */
    @Test
    void deletedTest() {
        // TODO: test deleted
    }

}
