/*
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com
 *
 * The version of the OpenAPI document: 1.75.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.ynab_api_client.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CurrencyFormat
 */
class CurrencyFormatTest {
    private final CurrencyFormat model = new CurrencyFormat();

    /**
     * Model tests for CurrencyFormat
     */
    @Test
    void testCurrencyFormat() {
        // TODO: test CurrencyFormat
    }

    /**
     * Test the property 'isoCode'
     */
    @Test
    void isoCodeTest() {
        // TODO: test isoCode
    }

    /**
     * Test the property 'exampleFormat'
     */
    @Test
    void exampleFormatTest() {
        // TODO: test exampleFormat
    }

    /**
     * Test the property 'decimalDigits'
     */
    @Test
    void decimalDigitsTest() {
        // TODO: test decimalDigits
    }

    /**
     * Test the property 'decimalSeparator'
     */
    @Test
    void decimalSeparatorTest() {
        // TODO: test decimalSeparator
    }

    /**
     * Test the property 'symbolFirst'
     */
    @Test
    void symbolFirstTest() {
        // TODO: test symbolFirst
    }

    /**
     * Test the property 'groupSeparator'
     */
    @Test
    void groupSeparatorTest() {
        // TODO: test groupSeparator
    }

    /**
     * Test the property 'currencySymbol'
     */
    @Test
    void currencySymbolTest() {
        // TODO: test currencySymbol
    }

    /**
     * Test the property 'displaySymbol'
     */
    @Test
    void displaySymbolTest() {
        // TODO: test displaySymbol
    }

}
