/*
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com
 *
 * The version of the OpenAPI document: 1.75.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.ynab_api_client.client.model;

import com.example.ynab_api_client.client.model.Category;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for MonthDetail
 */
class MonthDetailTest {
    private final MonthDetail model = new MonthDetail();

    /**
     * Model tests for MonthDetail
     */
    @Test
    void testMonthDetail() {
        // TODO: test MonthDetail
    }

    /**
     * Test the property 'month'
     */
    @Test
    void monthTest() {
        // TODO: test month
    }

    /**
     * Test the property 'note'
     */
    @Test
    void noteTest() {
        // TODO: test note
    }

    /**
     * Test the property 'income'
     */
    @Test
    void incomeTest() {
        // TODO: test income
    }

    /**
     * Test the property 'budgeted'
     */
    @Test
    void budgetedTest() {
        // TODO: test budgeted
    }

    /**
     * Test the property 'activity'
     */
    @Test
    void activityTest() {
        // TODO: test activity
    }

    /**
     * Test the property 'toBeBudgeted'
     */
    @Test
    void toBeBudgetedTest() {
        // TODO: test toBeBudgeted
    }

    /**
     * Test the property 'ageOfMoney'
     */
    @Test
    void ageOfMoneyTest() {
        // TODO: test ageOfMoney
    }

    /**
     * Test the property 'deleted'
     */
    @Test
    void deletedTest() {
        // TODO: test deleted
    }

    /**
     * Test the property 'categories'
     */
    @Test
    void categoriesTest() {
        // TODO: test categories
    }

}
