/*
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com
 *
 * The version of the OpenAPI document: 1.75.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.ynab_api_client.client.model;

import com.example.ynab_api_client.client.model.SaveSubTransaction;
import com.example.ynab_api_client.client.model.TransactionClearedStatus;
import com.example.ynab_api_client.client.model.TransactionFlagColor;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for NewTransaction
 */
class NewTransactionTest {
    private final NewTransaction model = new NewTransaction();

    /**
     * Model tests for NewTransaction
     */
    @Test
    void testNewTransaction() {
        // TODO: test NewTransaction
    }

    /**
     * Test the property 'accountId'
     */
    @Test
    void accountIdTest() {
        // TODO: test accountId
    }

    /**
     * Test the property 'date'
     */
    @Test
    void dateTest() {
        // TODO: test date
    }

    /**
     * Test the property 'amount'
     */
    @Test
    void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'payeeId'
     */
    @Test
    void payeeIdTest() {
        // TODO: test payeeId
    }

    /**
     * Test the property 'payeeName'
     */
    @Test
    void payeeNameTest() {
        // TODO: test payeeName
    }

    /**
     * Test the property 'categoryId'
     */
    @Test
    void categoryIdTest() {
        // TODO: test categoryId
    }

    /**
     * Test the property 'memo'
     */
    @Test
    void memoTest() {
        // TODO: test memo
    }

    /**
     * Test the property 'cleared'
     */
    @Test
    void clearedTest() {
        // TODO: test cleared
    }

    /**
     * Test the property 'approved'
     */
    @Test
    void approvedTest() {
        // TODO: test approved
    }

    /**
     * Test the property 'flagColor'
     */
    @Test
    void flagColorTest() {
        // TODO: test flagColor
    }

    /**
     * Test the property 'subtransactions'
     */
    @Test
    void subtransactionsTest() {
        // TODO: test subtransactions
    }

    /**
     * Test the property 'importId'
     */
    @Test
    void importIdTest() {
        // TODO: test importId
    }

}
